"""HDL generator (L2, spec §4/§7.4, R9/R11/R45-R50; AC-1-3 generator clause).

Lowers a HW-eligible pattern's byte automaton (:mod:`pyro.hdl.automaton`) into a
**synthesizable per-pattern Verilog-2001 circuit** that implements the fixed
harness contract of §7.4: the normative CSR register block (R45), the baked
circuit-identity block (R47a), result-ring semantics (R47), and START/DONE/OVF
single-issue control (R48).  The datapath is a generic one-hot NFA recognizer;
no vendor primitives and no timing-closure effort are attempted (Task-5 brief) —
that is Phase-2 work.  The circuit software model (:mod:`pyro._circuit_model`)
provides the behavioral reference; this RTL is the structural lowering that a
real synthesis flow (Phase 2) would consume.

Determinism (AC-1-3).  For a fixed ``(pattern, flags, generator_version)`` the
emitted text is **byte-identical**: state numbering, edge ordering and byte-set
ranges are all canonical (see :mod:`pyro.hdl.automaton`), and the emitter uses no
timestamps, hashes-of-object-ids, or dict-iteration order.
"""

from __future__ import annotations

import re._constants as _c
from typing import List, NamedTuple, Tuple

from . import automaton as _auto
from . import identity as _identity
from . import estimator as _estimator

# Generator / harness contract versions (packed MAJOR<<16|MINOR<<8|PATCH).
# This is the v2.0.0 per-pattern-circuit generator (spec §14 2.0.0 entry).
GENERATOR_VERSION = 0x00020000
HARNESS_VERSION = 0x00020000
DATAPATH_BYTES = 1  # one byte/cycle (R42 datapath_bytes); multi-byte is future.

ID_MAGIC = 0x5059524F  # "PYRO" (R45 offset 0x0000)

# Zero-width assertion -> Verilog condition wire (see the emitted anchor block).
# The parser emits AT_BEGINNING / AT_END for ^ / $ regardless of re.MULTILINE
# (line-vs-string semantics are flag-deferred, like re.DOTALL for '.'), so those
# two are resolved against the baked MULTILINE flag in :func:`_at_expr`.
_AT_EXPR = {
    _c.AT_BEGINNING_STRING: "at_sob",
    _c.AT_BEGINNING_LINE: "at_bol",
    _c.AT_END_STRING: "at_eob",
    _c.AT_END_LINE: "at_eol",
    _c.AT_BOUNDARY: "word_boundary",
    _c.AT_UNI_BOUNDARY: "word_boundary",
    _c.AT_NON_BOUNDARY: "(~word_boundary)",
    _c.AT_UNI_NON_BOUNDARY: "(~word_boundary)",
}


def _at_expr(at: int, multiline: bool):
    """Verilog condition for an AT_* assertion (None => always-true)."""
    if at == _c.AT_BEGINNING:
        return "at_bol" if multiline else "at_sob"
    if at == _c.AT_END:
        return "at_eol" if multiline else "at_eob"
    return _AT_EXPR.get(int(at))


class GeneratedCircuit(NamedTuple):
    """The artifact produced by :func:`generate` for one HW-eligible pattern."""

    pattern: object
    flags: int
    enc: int
    generator_version: int
    harness_version: int
    datapath_bytes: int
    automaton: _auto.Automaton
    circ_id: Tuple[int, int, int, int]  # CIRC_ID0..3 (R47a identity block)
    circ_flags: int                     # CIRC_FLAGS (R45 0x0028)
    num_patterns: int
    resources: dict
    rtl: str                            # synthesizable Verilog-2001 text

    # -- convenience accessors for the harness identity block (R47a) --------
    @property
    def pattern_hash16(self) -> bytes:
        return b"".join(w.to_bytes(4, "little") for w in self.circ_id)


def _ranges_expr(ranges: Tuple[Tuple[int, int], ...]) -> str:
    """Verilog boolean for ``in_data`` falling in any of ``ranges``."""
    terms = []
    for lo, hi in ranges:
        if lo == hi:
            terms.append(f"(in_data == 8'd{lo})")
        else:
            terms.append(f"(in_data >= 8'd{lo} && in_data <= 8'd{hi})")
    if not terms:
        return "1'b0"
    return " || ".join(terms)


def _emit_rtl(au: _auto.Automaton, circ_id, circ_flags, num_patterns) -> str:
    N = au.n_states
    L: List[str] = []
    add = L.append

    caps0 = (DATAPATH_BYTES & 0xFFFF) | ((_estimator.PR_PARTITIONS & 0xFFFF) << 16)

    add("// Auto-generated by pyro.hdl.generator — do not edit.")
    add("// Per-pattern PYRO recognizer implementing the §7.4 harness contract.")
    add(f"// generator_version=0x{GENERATOR_VERSION:08X} "
        f"harness_version=0x{HARNESS_VERSION:08X}")
    add("`timescale 1ns/1ps")
    add("module pyro_circuit (")
    add("    input  wire        clk,")
    add("    input  wire        rst_n,")
    add("    // AXI-Lite-style CSR window (§7.4 R45)")
    add("    input  wire [15:0] csr_addr,")
    add("    input  wire [31:0] csr_wdata,")
    add("    input  wire        csr_write,")
    add("    output reg  [31:0] csr_rdata,")
    add("    // input byte stream (DMA abstracted behind the harness, R48)")
    add("    input  wire        in_valid,")
    add("    input  wire [7:0]  in_data,")
    add("    input  wire        in_last,")
    add("    // result-ring write port (24-byte entries, R47)")
    add("    output reg         res_wr,")
    add("    output reg  [63:0] res_start,")
    add("    output reg  [63:0] res_end,")
    add("    output reg  [31:0] res_pattern_id,")
    add("    output reg  [31:0] res_flags")
    add(");")
    add("")
    add("    // --- normative harness constants (R45) ---")
    add(f"    localparam [31:0] MAGIC       = 32'h{ID_MAGIC:08X};")
    add(f"    localparam [31:0] HARNESS_VER = 32'h{HARNESS_VERSION:08X};")
    add(f"    localparam [31:0] GEN_VER     = 32'h{GENERATOR_VERSION:08X};")
    add(f"    localparam [31:0] CAPS0       = 32'h{caps0:08X};")
    add(f"    localparam [31:0] CIRC_ID0    = 32'h{circ_id[0]:08X};")
    add(f"    localparam [31:0] CIRC_ID1    = 32'h{circ_id[1]:08X};")
    add(f"    localparam [31:0] CIRC_ID2    = 32'h{circ_id[2]:08X};")
    add(f"    localparam [31:0] CIRC_ID3    = 32'h{circ_id[3]:08X};")
    add(f"    localparam [31:0] CIRC_FLAGS  = 32'h{circ_flags:08X};")
    add(f"    localparam integer NSTATES    = {N};")
    add(f"    localparam [31:0] START_STATE = 32'd{au.start};")
    add(f"    localparam [31:0] ACCEPT_STATE= 32'd{au.accept};")
    add("")
    add("    // --- CSR registers (R45) ---")
    add("    reg  [31:0] ctrl, status;")
    add("    reg  [31:0] in_addr_lo, in_addr_hi, in_len;")
    add("    reg  [31:0] out_addr_lo, out_addr_hi, out_cap, out_count;")
    add("    reg  [31:0] irq_enable, irq_status;")
    add("    wire        ctrl_start = ctrl[0];")
    add("    wire        ctrl_reset = ctrl[1];")
    add("")
    add("    // --- automaton state (one-hot NFA, R9 lowering) ---")
    add("    reg  [NSTATES-1:0] state_reg;   // registered active set")
    add("    reg  [NSTATES-1:0] active;      // eps/assert closure (comb)")
    add("    reg  [NSTATES-1:0] moved;       // byte-move result (comb)")
    add("    reg  [63:0] byte_index;")
    add("    reg  [7:0]  prev_byte;")
    add("    reg         have_prev;")
    add("    reg         running;")
    add("    integer     it;")
    add("")
    add("    // --- anchor/position condition wires (§6.5) ---")
    add("    wire at_sob = (byte_index == 64'd0);")
    add("    wire at_bol = at_sob || (have_prev && prev_byte == 8'h0A);")
    add("    wire at_eob = in_last;")
    add("    wire at_eol = in_last;  // structural; exact $ handled by the model")
    add("    wire cur_word  = (in_data >= 8'd48 && in_data <= 8'd57) ||")
    add("                     (in_data >= 8'd65 && in_data <= 8'd90) ||")
    add("                     (in_data >= 8'd97 && in_data <= 8'd122) ||")
    add("                     (in_data == 8'd95);")
    add("    wire prev_word = have_prev && ((prev_byte >= 8'd48 && prev_byte <= 8'd57) ||")
    add("                     (prev_byte >= 8'd65 && prev_byte <= 8'd90) ||")
    add("                     (prev_byte >= 8'd97 && prev_byte <= 8'd122) ||")
    add("                     (prev_byte == 8'd95));")
    add("    wire word_boundary = cur_word ^ prev_word;")
    add("")
    add("    // --- epsilon/assertion closure (combinational relaxation) ---")
    add("    always @(*) begin")
    add("        active = state_reg;")
    add("        for (it = 0; it < NSTATES; it = it + 1) begin")
    # emit eps/assert relaxation body (repeated NSTATES times by the for loop)
    multiline = bool(au.flags & 0x08)  # re.MULTILINE
    eps_lines = _emit_closure_body(au, multiline)
    for ln in eps_lines:
        add("            " + ln)
    add("        end")
    add("    end")
    add("")
    add("    // --- byte-move: consume in_data, seed a fresh start thread ---")
    add("    always @(*) begin")
    add("        moved = {NSTATES{1'b0}};")
    add("        moved[START_STATE] = 1'b1;  // continuous search seeding")
    move_lines = _emit_move_body(au)
    for ln in move_lines:
        add("        " + ln)
    add("    end")
    add("")
    add("    wire accept_hit = active[ACCEPT_STATE];")
    add("")
    add("    // --- sequential control / datapath (R48 single-issue) ---")
    add("    always @(posedge clk) begin")
    add("        if (!rst_n) begin")
    add("            ctrl <= 32'd0; status <= 32'd0; running <= 1'b0;")
    add("            in_addr_lo <= 32'd0; in_addr_hi <= 32'd0; in_len <= 32'd0;")
    add("            out_addr_lo <= 32'd0; out_addr_hi <= 32'd0;")
    add("            out_cap <= 32'd0; out_count <= 32'd0;")
    add("            irq_enable <= 32'd0; irq_status <= 32'd0;")
    add("            state_reg <= {NSTATES{1'b0}};")
    add("            byte_index <= 64'd0; prev_byte <= 8'd0; have_prev <= 1'b0;")
    add("            res_wr <= 1'b0; res_start <= 64'd0; res_end <= 64'd0;")
    add("            res_pattern_id <= 32'd0; res_flags <= 32'd0;")
    add("        end else begin")
    add("            res_wr <= 1'b0;")
    add("            // CSR writes (RW registers only; RO ignored)")
    add("            if (csr_write) begin")
    add("                case (csr_addr)")
    add("                    16'h0010: ctrl <= csr_wdata;")
    add("                    16'h0030: in_addr_lo <= csr_wdata;")
    add("                    16'h0034: in_addr_hi <= csr_wdata;")
    add("                    16'h0038: in_len <= csr_wdata;")
    add("                    16'h0040: out_addr_lo <= csr_wdata;")
    add("                    16'h0044: out_addr_hi <= csr_wdata;")
    add("                    16'h0048: out_cap <= csr_wdata;")
    add("                    16'h0050: irq_enable <= csr_wdata;")
    add("                    16'h0054: irq_status <= irq_status & ~csr_wdata;")
    add("                    default: ;")
    add("                endcase")
    add("            end")
    add("            if (ctrl_reset) begin")
    add("                state_reg <= {NSTATES{1'b0}};")
    add("                byte_index <= 64'd0; have_prev <= 1'b0;")
    add("                out_count <= 32'd0; running <= 1'b0; status <= 32'd0;")
    add("            end else if (ctrl_start && !running) begin")
    add("                running <= 1'b1;")
    add("                status <= 32'h0000_0001;  // BUSY")
    add("                state_reg <= {NSTATES{1'b0}};")
    add("                state_reg[START_STATE] <= 1'b1;")
    add("                byte_index <= 64'd0; have_prev <= 1'b0; out_count <= 32'd0;")
    add("            end else if (running && in_valid) begin")
    add("                state_reg <= moved;")
    add("                prev_byte <= in_data; have_prev <= 1'b1;")
    add("                byte_index <= byte_index + 64'd1;")
    add("                if (accept_hit) begin")
    add("                    if (out_count < out_cap) begin")
    add("                        res_wr <= 1'b1;")
    add("                        res_start <= 64'd0;  // start tracked host-side")
    add("                        res_end <= byte_index + 64'd1;")
    add("                        res_pattern_id <= 32'd0;")
    add("                        res_flags <= 32'd1;  // bit0 verified (advisory)")
    add("                        out_count <= out_count + 32'd1;")
    add("                    end else begin")
    add("                        status <= status | 32'h0000_0008;  // OVF")
    add("                    end")
    add("                end")
    add("                if (in_last) begin")
    add("                    running <= 1'b0;")
    add("                    status <= (status & ~32'h0000_0001) | 32'h0000_0002;")
    add("                    irq_status <= irq_status | 32'h0000_0001;")
    add("                end")
    add("            end")
    add("        end")
    add("    end")
    add("")
    add("    // --- CSR read mux (R45 offsets; all RO/RW registers) ---")
    add("    always @(*) begin")
    add("        case (csr_addr)")
    add("            16'h0000: csr_rdata = MAGIC;")
    add("            16'h0004: csr_rdata = HARNESS_VER;")
    add("            16'h0008: csr_rdata = CAPS0;")
    add("            16'h000C: csr_rdata = GEN_VER;")
    add("            16'h0010: csr_rdata = ctrl;")
    add("            16'h0014: csr_rdata = status;")
    add("            16'h0018: csr_rdata = CIRC_ID0;")
    add("            16'h001C: csr_rdata = CIRC_ID1;")
    add("            16'h0020: csr_rdata = CIRC_ID2;")
    add("            16'h0024: csr_rdata = CIRC_ID3;")
    add("            16'h0028: csr_rdata = CIRC_FLAGS;")
    add("            16'h002C: csr_rdata = 32'd0;")
    add("            16'h0030: csr_rdata = in_addr_lo;")
    add("            16'h0034: csr_rdata = in_addr_hi;")
    add("            16'h0038: csr_rdata = in_len;")
    add("            16'h0040: csr_rdata = out_addr_lo;")
    add("            16'h0044: csr_rdata = out_addr_hi;")
    add("            16'h0048: csr_rdata = out_cap;")
    add("            16'h004C: csr_rdata = out_count;")
    add("            16'h0050: csr_rdata = irq_enable;")
    add("            16'h0054: csr_rdata = irq_status;")
    add("            default:  csr_rdata = 32'd0;")
    add("        endcase")
    add("    end")
    add("endmodule")
    add("")
    return "\n".join(L)


def _emit_closure_body(au: _auto.Automaton, multiline: bool) -> List[str]:
    """Relaxation body: propagate eps/assert edges into ``active`` once."""
    lines: List[str] = []
    for s in range(au.n_states):
        for e in au.sorted_edges(s):
            if e.kind == _auto.E_EPS:
                lines.append(
                    f"if (active[{s}]) active[{e.target}] = 1'b1;")
            elif e.kind == _auto.E_ASSERT:
                cond = _at_expr(int(e.payload), multiline)
                if cond is None:
                    # OVER-APPROX: unknown assertion treated as always-true.
                    lines.append(
                        f"if (active[{s}]) active[{e.target}] = 1'b1;")
                else:
                    lines.append(
                        f"if (active[{s}] && {cond}) active[{e.target}] = 1'b1;")
    if not lines:
        lines.append("active = active;  // no epsilon/assert edges")
    return lines


def _emit_move_body(au: _auto.Automaton) -> List[str]:
    """Byte-move body: for each byte edge, gate on source active + byte match."""
    lines: List[str] = []
    for src, ranges, dst in au.byte_edges():
        expr = _ranges_expr(ranges)
        lines.append(f"if (active[{src}] && ({expr})) moved[{dst}] = 1'b1;")
    if not lines:
        lines.append("moved = moved;  // no byte edges")
    return lines


def generate(pattern, flags: int = 0, enc: int = None) -> GeneratedCircuit:
    """Generate the per-pattern circuit for a HW-eligible ``(pattern, flags)``.

    Raises ``ValueError`` if the pattern is not HW-eligible or does not fit the
    advertised budget (callers gate with the estimator / classifier first; this
    guard keeps a bad pattern from ever producing RTL, R12).
    """
    est = _estimator.estimate(pattern, flags, enc)
    if not est.eligible:
        raise ValueError(f"pattern not HW-eligible: {est.reason}")

    au = _auto.build(pattern, flags, enc)
    digest = _identity.pattern_hash(
        pattern, au.flags, GENERATOR_VERSION, HARNESS_VERSION)
    circ_id = _identity.circ_id_words(digest)
    num_patterns = est.resources["num_patterns"]
    circ_flags = _identity.circ_flags_word(au.flags, num_patterns)

    rtl = _emit_rtl(au, circ_id, circ_flags, num_patterns)
    return GeneratedCircuit(
        pattern=pattern,
        flags=int(flags),
        enc=au.enc,
        generator_version=GENERATOR_VERSION,
        harness_version=HARNESS_VERSION,
        datapath_bytes=DATAPATH_BYTES,
        automaton=au,
        circ_id=circ_id,
        circ_flags=circ_flags,
        num_patterns=num_patterns,
        resources=est.resources,
        rtl=rtl,
    )
