"""S4 ROM-child emitters: table image -> $readmemh files + alias top.

The ROM engine (``hw/rtl/pyro_ac_rom_engine.v``) holds the same six
arrays as the A5 overlay engine, but their content is baked at synthesis
from ``.memh`` files instead of arriving over the R78 load path.  This
module turns a serialized table image (``pyro.overlay.table.serialize``)
into those files, byte-for-byte the way the load path would have written
the arrays — the emitter slices the *image*, not the automaton, so the
serializer stays the single source of layout truth.

Word packing mirrors the RTL load accumulators exactly: the engine
shifts bytes in from the top of each shift register, so after N bytes
the FIRST byte received is the LOW byte — i.e. every array word is the
little-endian reading of its image bytes.  ``oidx`` is therefore
``(count << 32) | offset`` from the image's ``<II`` (offset, count).

The alias top is GENERATED (unlike the A5 one, which is static) because
its parameters — array sizes, baked TABLE_ID — are functions of the
built table.  It still lands as a module named ``pyro_circuit`` so
``rp_wrapper`` picks it up unchanged.
"""

from __future__ import annotations

import os
import struct
from typing import Dict

from ..overlay import table as _otable

#: File names the ROM engine's $readmemh defaults expect (relative to
#: the tool CWD — the build script and the xsim runner both copy them
#: into the working directory).
MEMH_FILES = ("s4_bitmap.memh", "s4_base.memh", "s4_dense.memh",
              "s4_fail.memh", "s4_oidx.memh", "s4_oflat.memh")


def _words(section: bytes, nbytes: int, digits: int) -> list:
    """Little-endian ``nbytes``-wide words as fixed-width hex lines."""
    return ["%0*x" % (digits, int.from_bytes(section[i:i + nbytes],
                                             "little"))
            for i in range(0, len(section), nbytes)]


def emit_memh(image: bytes, outdir: str) -> Dict[str, int]:
    """Write the six ``.memh`` files for ``image`` into ``outdir``.

    Returns the geometry the alias top needs.  Refuses an image whose
    header does not parse — a ROM baked from a malformed image would be
    the silent-wrong-table failure A5 §5 exists to prevent.
    """
    (magic, version, engine_id, n_states, n_patterns,
     o_bm, o_base, o_dense, o_fail, o_oidx, o_oflat,
     n_dense, n_oflat) = struct.unpack_from(_otable._HDR_FMT, image, 0)
    if magic != _otable.TABLE_MAGIC or \
            version != _otable.TABLE_FORMAT_VERSION:
        raise ValueError("not a serialized PYRO table image")

    sections = {
        "s4_bitmap.memh": (image[o_bm:o_base], 32, 64),
        "s4_base.memh": (image[o_base:o_dense], 4, 8),
        "s4_dense.memh": (image[o_dense:o_fail], 4, 8),
        "s4_fail.memh": (image[o_fail:o_oidx], 4, 8),
        "s4_oidx.memh": (image[o_oidx:o_oflat], 8, 16),
        # $readmemh into a zero-entry array is an error, and a trie
        # with no outputs matches nothing and cannot be built here —
        # but n_oflat can legitimately be small; only truly-empty is
        # padded with one dead word (MAX_OUT is sized >= 1 to match).
        "s4_oflat.memh": (image[o_oflat:] or b"\0\0\0\0", 4, 8),
    }
    for name, (sec, nbytes, digits) in sections.items():
        with open(os.path.join(outdir, name), "w") as f:
            f.write("\n".join(_words(sec, nbytes, digits)) + "\n")

    return {
        "n_states": n_states,
        "n_patterns": n_patterns,
        "n_dense": n_dense,
        "n_oflat": max(1, n_oflat),
        "engine_id": engine_id,
        "table_id": _otable.table_id(image),
        "image_bytes": len(image),
    }


_ALIAS_TEMPLATE = """\
// GENERATED by pyro.hdl.rom_child — do not edit.
//
// S4 ROM child alias: `rp_wrapper` instantiates a module literally
// named `pyro_circuit` (ENGINE_MODULE); this one binds it to the ROM
// engine with the geometry and identity of the table baked into this
// exact build.  TABLE_ID here is the CRC-32C the host serializer
// computed for the image the .memh files carry, so an attribution
// against this child names the ruleset build, not just the engine.
`timescale 1ns/1ps
`default_nettype none

module pyro_circuit (
    input  wire        clk,
    input  wire        rst_n,
    input  wire [15:0] csr_addr,
    input  wire [31:0] csr_wdata,
    input  wire        csr_write,
    output wire [31:0] csr_rdata,
    input  wire        in_valid,
    input  wire [7:0]  in_data,
    input  wire        in_last,
    output wire        in_ready,
    output wire        res_wr,
    output wire [63:0] res_start,
    output wire [63:0] res_end,
    output wire [31:0] res_pattern_id,
    output wire [31:0] res_flags
);
    pyro_ac_rom_engine #(
        .MAX_STATES(@N_STATES@),
        .MAX_DENSE(@N_DENSE@),
        .MAX_OUT(@N_OFLAT@),
        .ENGINE_ID(32'h@ENGINE_ID@),
        .TABLE_ID(32'h@TABLE_ID@),
        .TABLE_EPOCH(32'h@EPOCH@),
        .IMAGE_BYTES(@IMAGE_BYTES@)
    ) u_engine (
        .clk(clk), .rst_n(rst_n),
        .csr_addr(csr_addr), .csr_wdata(csr_wdata),
        .csr_write(csr_write), .csr_rdata(csr_rdata),
        .in_valid(in_valid), .in_data(in_data), .in_last(in_last),
        .in_ready(in_ready),
        .res_wr(res_wr), .res_start(res_start), .res_end(res_end),
        .res_pattern_id(res_pattern_id), .res_flags(res_flags)
    );
endmodule

`default_nettype wire
"""


def alias_verilog(geom: Dict[str, int], epoch: int = 1) -> str:
    """The generated ``pyro_circuit`` alias for ``geom`` (emit_memh's
    return value)."""
    if not (0 < epoch <= 0xFFFFFFFF):
        raise ValueError("epoch must be non-zero (0 = no valid table)")
    return (_ALIAS_TEMPLATE
            .replace("@N_STATES@", str(geom["n_states"]))
            .replace("@N_DENSE@", str(max(1, geom["n_dense"])))
            .replace("@N_OFLAT@", str(max(1, geom["n_oflat"])))
            .replace("@ENGINE_ID@", "%08x" % geom["engine_id"])
            .replace("@TABLE_ID@", "%08x" % geom["table_id"])
            .replace("@EPOCH@", "%08x" % epoch)
            .replace("@IMAGE_BYTES@", str(geom["image_bytes"])))
