#!/usr/bin/env python3
"""Generate build/include/pyro_thresholds.h from pyro/_thresholds.py.

ANTI-DRIFT (see the contract in the Phase-3 design): there is exactly ONE
literal for S_min / N_reuse in this tree, and it lives in pyro/_thresholds.py.
The native routing core must never carry its own copy, so its header is
generated here — by BOTH the Makefile (`make ext`) and setup.py's build_ext.

The generated header is a build artifact and is not committed (build/ is
already .gitignore'd).
"""
from __future__ import annotations

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SRC = os.path.join(ROOT, "pyro", "_thresholds.py")
DEFAULT_OUT = os.path.join(ROOT, "build", "include", "pyro_thresholds.h")


def load_thresholds(path: str):
    """exec the literal-only threshold module in a bare namespace (no import of
    the `pyro` package, so this runs before/without a built extension)."""
    ns: dict = {}
    with open(path, "r", encoding="utf-8") as fh:
        exec(compile(fh.read(), path, "exec"), ns)   # noqa: S102 - trusted, in-tree
    return int(ns["S_MIN"]), int(ns["N_REUSE"])


def render(s_min: int, n_reuse: int, src: str) -> str:
    return f"""/* GENERATED by scripts/gen_route_config.py from {os.path.relpath(src, ROOT)}
 * DO NOT EDIT.  The single source of truth for these thresholds is
 * pyro/_thresholds.py; the C never carries its own literal.
 */
#ifndef PYRO_THRESHOLDS_H
#define PYRO_THRESHOLDS_H

#define PYRO_S_MIN   {s_min}u   /* R2/R51 step 4: minimum corpus size */
#define PYRO_N_REUSE {n_reuse}u   /* R2/R51 step 4: per-pattern reuse threshold */

#endif /* PYRO_THRESHOLDS_H */
"""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", default=DEFAULT_SRC)
    ap.add_argument("--out", default=DEFAULT_OUT)
    args = ap.parse_args(argv)

    s_min, n_reuse = load_thresholds(args.src)
    text = render(s_min, n_reuse, args.src)

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    # Idempotent write: do not touch the mtime when nothing changed, so make
    # does not needlessly rebuild the extension.
    try:
        with open(args.out, "r", encoding="utf-8") as fh:
            if fh.read() == text:
                return 0
    except OSError:
        pass
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
