/* pyro_route.h — the native R51 routing-decision core.
 *
 * This header is DELIBERATELY NOT part of the frozen C ABI 2.0.0 surface
 * (include/pyro_rt.h): `make abi-check` asserts pyro_abi_version() ==
 * 0x00020000 and that surface is frozen (R37/R38).  The routing core is an
 * internal, statically-linked-into-the-extension decision function; it exports
 * no device/runtime symbols and carries no ABI promise.
 *
 * The decision itself (steps S1..S6 of the contract, i.e. the §8 R51 decision
 * minus the O(n) UTF-8 transportability probe, which is model-bound-only and
 * stays in Python) is provided as a `static inline` so the CPython
 * interposition extension reaches it by a DIRECT C call with no PLT hop and no
 * ctypes boundary (R3c.1; a ctypes hop measures 175.9 ns = 4.5x the entire R3b
 * budget).  src/pyro_route.c additionally emits a non-inline `pyro_route_decide`
 * for standalone C consumers / tests.
 *
 * The thresholds are NOT written here.  They come from build/include/
 * pyro_thresholds.h, generated by scripts/gen_route_config.py from
 * pyro/_thresholds.py — the single source of truth for S_MIN / N_REUSE.
 */
#ifndef PYRO_ROUTE_H
#define PYRO_ROUTE_H

#include <stdint.h>

#include "pyro_thresholds.h"   /* generated: PYRO_S_MIN, PYRO_N_REUSE */

#ifdef __cplusplus
extern "C" {
#endif

#define PYRO_ROUTE_FALLBACK 0
#define PYRO_ROUTE_MODEL    1

/* Every input the decision is allowed to read.  Nothing else may be consulted:
 * in particular never os.environ (R35a/R5) and never a Python attribute chain. */
typedef struct {
    uint64_t subj_len;    /* len(string) in CALLER units: code points for str,
                           * bytes for bytes.  Only meaningful when exact_type. */
    uint64_t reuse;       /* patt._calls BEFORE the S0 increment */
    uint8_t  disabled;    /* cached PYRO_DISABLE      (R51.1) */
    uint8_t  force;       /* cached PYRO_FORCE_MODEL  (R51.4) */
    uint8_t  eligible;    /* patt._classification.eligible (R51.2) */
    uint8_t  exact_type;  /* type(string) is exactly str or bytes (R51a(a)) */
    uint8_t  full_span;   /* pos == 0 and (endpos is None or endpos >= len)  */
} pyro_route_in;

/* S1..S6, in the normative order.  Pure: no allocation, no locks, no I/O. */
static inline int pyro_route_decide_inline(const pyro_route_in *in)
{
    if (in->disabled)      return PYRO_ROUTE_FALLBACK;   /* S1  R51.1      */
    if (!in->eligible)     return PYRO_ROUTE_FALLBACK;   /* S2  R51.2      */
    if (!in->exact_type)   return PYRO_ROUTE_FALLBACK;   /* S3  R51a(a)    */
    if (!in->full_span)    return PYRO_ROUTE_FALLBACK;   /* S4  R51a(b/c)  */
    if (!in->force && in->subj_len < (uint64_t)PYRO_S_MIN
                   && in->reuse    < (uint64_t)PYRO_N_REUSE)
        return PYRO_ROUTE_FALLBACK;                      /* S5  R51.4/R3a  */
    return PYRO_ROUTE_MODEL;                             /* S6  R51.6      */
}

/* Non-inline entry point (same semantics), for standalone C callers. */
int pyro_route_decide(const pyro_route_in *in);

/* The compiled-in thresholds, so a caller can prove its copy agrees. */
uint64_t pyro_route_s_min(void);
uint64_t pyro_route_n_reuse(void);

#ifdef __cplusplus
}
#endif

#endif /* PYRO_ROUTE_H */
