"""Lower a group's anchor list to Snort 2.9 content-only rules.

One rule per anchor, per docs/studies/fpga-vs-snort.md section 2:

    alert tcp any any -> any any (msg:"..."; content:"..."; \
        sid:1000000+i; rev:1;)

Pattern identity: the caller passes the group's SORTED UNIQUE anchor
byte-string list (pyro.quantify.traffic.unique_patterns); position in
that list is the pattern index and sid = 1000000 + index.  Snort's
fast-pattern matcher then searches exactly the literal set the A5
table was built from.

Content escaping (validated against the local Snort 2.9.20 build):
printable ASCII 0x20-0x7E is emitted raw EXCEPT the four bytes that
are rule-syntax inside content strings -- ';' '"' '|' '\\' -- which,
along with every non-printable byte, are pipe-hex escaped as |XX| (a
single pipe pair covers a run: |3B 22 00|).

Also emits the two-line .conf that pins the ac-q search method (full
Aho-Corasick, queued -- the software analog of the A5 engine) and
includes the rules file by absolute path so the -c invocation is
cwd-independent.
"""

import os
import re

SID_BASE = 1000000

# Bytes emitted raw inside content:"...": printable ASCII minus the
# four content-syntax bytes ; " | backslash.
_RAW_OK = frozenset(
    b for b in range(0x20, 0x7F)
    if b not in (0x3B, 0x22, 0x7C, 0x5C))

RULE_TEMPLATE = ('alert tcp any any -> any any '
                 '(msg:"pyro-quantify %s pat %d"; content:"%s"; '
                 'sid:%d; rev:1;)')

CONF_TEMPLATE = ("config detection: search-method ac-q\n"
                 "include %s\n")


def sanitize_name(group_name):
    """Filesystem-safe stem for a group name like "$SIP_PORTS/0"."""
    stem = re.sub(r"[^A-Za-z0-9._-]+", "_", group_name).strip("_.")
    return stem or "group"


def escape_content(anchor):
    """Escape anchor bytes for a Snort content:"..." string."""
    out = []
    run = []

    def flush():
        if run:
            out.append("|%s|" % " ".join("%02X" % b for b in run))
            del run[:]

    for b in bytes(anchor):
        if b in _RAW_OK:
            flush()
            out.append(chr(b))
        else:
            run.append(b)
    flush()
    return "".join(out)


def unescape_content(text):
    """Inverse of escape_content (for tests and referees)."""
    out = bytearray()
    i = 0
    n = len(text)
    while i < n:
        c = text[i]
        if c == "|":
            j = text.index("|", i + 1)
            for tok in text[i + 1:j].split():
                out.append(int(tok, 16))
            i = j + 1
        else:
            out.append(ord(c))
            i += 1
    return bytes(out)


def rule_line(group_stem, index, anchor):
    """One Snort 2 rule; sid = SID_BASE + index."""
    return RULE_TEMPLATE % (group_stem, index,
                            escape_content(anchor), SID_BASE + index)


def write_rules(outdir, anchors, group_name):
    """Write <stem>.rules and <stem>.conf under outdir.

    anchors is the sorted unique anchor list (index i -> sid
    SID_BASE + i).  An empty list writes an empty rules file (the
    decode-only baseline).  Returns (rules_path, conf_path).
    """
    os.makedirs(outdir, exist_ok=True)
    stem = sanitize_name(group_name)
    rules_path = os.path.join(outdir, stem + ".rules")
    conf_path = os.path.join(outdir, stem + ".conf")

    lines = ["# generated by pyro.quantify.snort_lower for group %s"
             % group_name]
    for i, anchor in enumerate(anchors):
        if not anchor:
            raise ValueError("empty/None anchor at index %d" % i)
        lines.append(rule_line(stem, i, anchor))
    with open(rules_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    with open(conf_path, "w") as f:
        f.write(CONF_TEMPLATE % os.path.abspath(rules_path))
    return rules_path, conf_path
